version: "3"

services:
  nginx:
    hostname: 127.0.0.1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webcalc
    image: krzywon/nginx:webcalc
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/etc:/etc/nginx/ssl
      - /dev/log:/dev/log:z

  webcalc:
    image: krzywon/webcalc:latest
    ports:
      - 5000:5000
    restart: always