version: "3"

services:
  nginx:
    hostname: 127.0.0.1
    ports:
      - 80:80
    depends_on:
      - webcalc
    image: nginx:latest
    restart: always

  webcalc:
    image: krzywon/webcalc:latest
    ports:
      - 5000:5000
    restart: always